spring:
  application:
    name: provider

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://ying:123@localhost:8761/eureka/
  #eureka.instance.prefer-ip-address  表示将自己的IP注册到Eureka Server上，
  #如果不配置,会将当前服务提供者所在的主机名注册到Eureka Server上。
  instance:
    prefer-ip-address: true

security:
  basic:
    enabled: false