spring:
  application:
    name: server

server:
  port: 8761
eureka:
  client:
    #表示是否将自己注册到Eureka Server上，默认为true，当前应用为Eureka Server所以无需注册
    register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
    fetch-registry: false

security:
  basic:
    enabled: true
  user:
    name: ying
    password: 123