spring:
  application:
    name: order
  cloud:
    stream:
      bindings:
        #配置自己定义的通道与哪个中间件交互
        shop_input: #ShopChannel里Input和Output的值
          destination: zhibo #目标主题
        shop_output:
          destination: zhibo
      default-binder: kafka #默认的binder是kafka
    kafka:
      bootstrap-servers: 192.168.31.205:9092 #kafka服务地址
      consumer:
        group-id: consumer1
      producer:
        key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
        value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
        client-id: producer1

server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://ying:123@localhost:8761/eureka/
  #eureka.instance.prefer-ip-address  表示将自己的IP注册到Eureka Server上，
  #如果不配置,会将当前服务提供者所在的主机名注册到Eureka Server上。
  instance:
    prefer-ip-address: true

security:
  basic:
    enabled: false
