spring:
  application:
    name: consumer
  redis:
    database: 1
    host: 192.168.31.205
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    timeout: 5000

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://ying:123@localhost:8761/eureka/
  #eureka.instance.prefer-ip-address  表示将自己的IP注册到Eureka Server上，
  #如果不配置,会将当前服务提供者所在的主机名注册到Eureka Server上。
  instance:
    prefer-ip-address: true

security:
  basic:
    enabled: false

zuul:
  routes:
    api-a:
      path: /order/**
      serviceId: order
    api-b:
      path: /provider/**
      serviceId: provider